# Generated by Django 2.2 on 2022-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(null=True, verbose_name='Cholesterol (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_fibre',
            field=models.FloatField(null=True, verbose_name='Dietary Fibre (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(null=True, verbose_name='Protein (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(null=True, verbose_name='Sodium (mg)'),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(null=True, verbose_name='Sugar (g)'),
        ),
        migrations.AddField(
            model_name='food',
            name='total_carbohydrate',
            field=models.FloatField(null=True, verbose_name='Total Carbohydrate (g)'),
        ),
    ]
